# Generated by Django 4.2.2 on 2023-06-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='titile',
            new_name='title',
        ),
    ]
